/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-09 15:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.vo.BoardVO;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1633590731731L));
    _jspx_dependants.put("jar:file:/D:/JspWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.vo.BoardVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    BoardVO vo = (BoardVO) request.getAttribute("vo");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>content.jsp</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \r\n");
      out.write("\r\n");
      out.write("<!-- 링크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- jquery.ui  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script> \r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<style>\r\n");
      out.write("  table{\r\n");
      out.write("     border-spacing: 3px;\r\n");
      out.write("     border-collapse: separate; \r\n");
      out.write("   }\r\n");
      out.write("   table,  tr, td {\r\n");
      out.write("      border:solid 1px gray;\r\n");
      out.write("      /* border-radius: 3px;  \r\n");
      out.write("      padding:3px;   */ \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write(" #tblContent{\r\n");
      out.write("   width:600px;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function (){	  \r\n");
      out.write("	   \r\n");
      out.write("	   $(\"#homeLink\")\r\n");
      out.write("	     .attr(\"href\"\r\n");
      out.write("	   , \"/bb/List\");\r\n");
      out.write("	   \r\n");
      out.write("	   $(\"#btnModalDelete\").on(\"click\", function(event) {\r\n");
      out.write("		   // 객체.메서드(\"open\")\r\n");
      out.write("	   	  dialog.dialog(\"open\");\r\n");
      out.write("	   });\r\n");
      out.write("	   \r\n");
      out.write("	   $(\"#cancel\").on(\"click\", function(event) {\r\n");
      out.write("		   // 객체.메서드(\"open\")\r\n");
      out.write("		   	  dialog.dialog(\"close\");\r\n");
      out.write("		   });\r\n");
      out.write("	   \r\n");
      out.write("	   dialog = $( \"#dialog-form\" ).dialog({\r\n");
      out.write("		      autoOpen: false,\r\n");
      out.write("		      height: 400,\r\n");
      out.write("		      width: 350,\r\n");
      out.write("		      modal: true,\r\n");
      out.write("		      buttons: {\r\n");
      out.write("		        /* \"Create an account\": addUser,\r\n");
      out.write("		        Cancel: function() {\r\n");
      out.write("		          dialog.dialog( \"close\" );\r\n");
      out.write("		        } */\r\n");
      out.write("		      },\r\n");
      out.write("		      close: function() {\r\n");
      out.write("		         form[ 0 ].reset();\r\n");
      out.write("		         //allFields.removeClass( \"ui-state-error\" );\r\n");
      out.write("		      }\r\n");
      out.write("		    });\r\n");
      out.write("		 \r\n");
      out.write("		 form = dialog.find( \"form\" );\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write(" <div align=\"center\">\r\n");
      out.write("  <h2>내용보기</h2>\r\n");
      out.write("  <table id=\"tblContent\">\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td>이름</td>\r\n");
      out.write("       <td>");
      out.print( vo.getWriter() );
      out.write("</td>\r\n");
      out.write("       <td>등록일</td>\r\n");
      out.write("       <td>");
      out.print( vo.getWritedate() );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td>Email</td>\r\n");
      out.write("       <td><a href=\"mailto:");
      out.print( vo.getEmail() );
      out.write('"');
      out.write('>');
      out.print( vo.getEmail() );
      out.write("</a></td>\r\n");
      out.write("       <td>조회</td>\r\n");
      out.write("       <td>");
      out.print( vo.getReaded() );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("        <td>제목</td>\r\n");
      out.write("        <td colspan=\"3\">");
      out.print( vo.getTitle() );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("        <td>첨부파일</td>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td colspan=\"4\" style=\"padding:15px;height: 200px;text-align: left;vertical-align: top\">\r\n");
      out.write("       ");
      out.print( vo.getContent() );
      out.write("\r\n");
      out.write("       </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td colspan=\"4\" align=\"center\" >\r\n");
      out.write("           <a class=\"btn btn-secondary\"  href=\"/bb/Edit?seq=");
      out.print( vo.getSeq() );
      out.write("\" id=\"editLink\">수정하기</a>\r\n");
      out.write("           <a class=\"btn btn-secondary\"  href=\"List\" id=\"homeLink\">게시판으로</a>\r\n");
      out.write("           <input class=\"btn btn-secondary\"  type=\"button\" id=\"btnModalDelete\" value=\"글 삭제\"> \r\n");
      out.write("           \r\n");
      out.write("       </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--  삭제 모달창 -->\r\n");
      out.write("<div id=\"dialog-form\" align=\"center\" title=\"삭제\">\r\n");
      out.write("  <h2>삭제하기</h2>\r\n");
      out.write("  <form action=\"Delete\" method=\"post\">\r\n");
      out.write("       \r\n");
      out.write("    <table>\r\n");
      out.write("	  <tr>\r\n");
      out.write("	    <td colspan=\"2\" align=\"center\"><b>글을 삭제합니다</b></td>\r\n");
      out.write("	  </tr>\r\n");
      out.write("	  <tr>\r\n");
      out.write("	    <td align=\"center\">비밀번호</td>\r\n");
      out.write("	    <td>\r\n");
      out.write("	      <input type=\"password\" name=\"pwd\" size=\"15\" autofocus=\"autofocus\">\r\n");
      out.write("	    </td>\r\n");
      out.write("	  </tr>\r\n");
      out.write("	  <tr>\r\n");
      out.write("	    <td colspan=\"2\" align=\"center\">\r\n");
      out.write("	      <input type=\"submit\" value=\"삭제\">&nbsp;&nbsp;\r\n");
      out.write("	      <!-- <input type=\"button\" onClick=\"javascript:history.back();\" value=\"취소\"> -->\r\n");
      out.write("	      <input type=\"button\" id=\"cancel\" value=\"취소\">\r\n");
      out.write("	    </td>\r\n");
      out.write("	  </tr>\r\n");
      out.write("	</table> \r\n");
      out.write("	<input type=\"hidden\" name=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.seq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("	        \r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
