/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-10-18 15:01:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.vo.PageBlock;
import java.util.Iterator;
import com.vo.BoardVO;
import java.util.ArrayList;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1633590731731L));
    _jspx_dependants.put("jar:file:/D:/JspWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.vo.BoardVO");
    _jspx_imports_classes.add("com.vo.PageBlock");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    ArrayList<BoardVO> list =
                           (ArrayList<BoardVO>)request.getAttribute("list");

    PageBlock pageBlock =  (PageBlock)request.getAttribute("pageBlock");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>list.jsp</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- 링크 -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"../css/style_list.css\"> -->\r\n");
      out.write("<style>\r\n");
      out.write("table, td, th {\r\n");
      out.write("	border: solid 1px gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-spacing: 3px;\r\n");
      out.write("	border-collapse: separate;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, tr, td {\r\n");
      out.write("	/* border-radius: 3px; */\r\n");
      out.write("	/* padding:3px;  */\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody tr  td:nth-of-type(2) {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 페이징 처리 style -->\r\n");
      out.write("<style>\r\n");
      out.write(".pagination {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding: 4px 8px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: background-color .3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a.active {\r\n");
      out.write("	background-color: dodgerblue;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a:hover:not (.active ) {\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".searchWord {\r\n");
      out.write("	background-color: yellow;\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".title {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function (){	  \r\n");
      out.write("	   // Write?write=success\r\n");
      out.write("	   if( '");
      out.print( request.getParameter("write") );
      out.write("' == 'success' ){\r\n");
      out.write("		   alert(\"글 쓰기 완료!!!\");\r\n");
      out.write("	   }		   \r\n");
      out.write("	   \r\n");
      out.write("	   // 상태 유지\r\n");
      out.write("	   $(\"#searchCondition\").val( '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${  requestScope.searchCondition }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'); \r\n");
      out.write("	   $(\"#searchWord\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ param.searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- <h3>list.jsp</h3> -->\r\n");
      out.write(" <div align=\"center\">\r\n");
      out.write("  <h2>목록 보기</h2>\r\n");
      out.write("  <a href=\"/bb/index.jsp\">메인페이지</a>\r\n");
      out.write("  <a href=\"/bb/Write\">글쓰기</a>\r\n");
      out.write("  <table style=\"width:600px;\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=\"10%\">번호</th>\r\n");
      out.write("        <th width=\"45%\">제목</th>\r\n");
      out.write("        <th width=\"17%\">작성자</th>\r\n");
      out.write("        <th width=\"20%\">등록일</th>\r\n");
      out.write("        <th width=\"10%\">조회</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    ");

        if( list == null ){
   
      out.write("\r\n");
      out.write("      <tr><td colspan=\"5\">등록된 게시글이 없습니다.</td></tr>\r\n");
      out.write("   ");
     	
        }else{
        	Iterator<BoardVO> ir = list.iterator();
        	while( ir.hasNext() ){
        		BoardVO vo = ir.next();
   
      out.write("\r\n");
      out.write("      <tr align=\"center\">\r\n");
      out.write("        <td>");
      out.print( vo.getSeq() );
      out.write("</td>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <td>\r\n");
      out.write("           <a class=\"title\" href=\"/bb/Content?seq=");
      out.print( vo.getSeq() );
      out.write('"');
      out.write('>');
      out.print( vo.getTitle() );
      out.write("</a>\r\n");
      out.write("           ");

              if( vo.isNewmark() ){
           
      out.write("<img src=\"D:\\JspWork\\bb5\\WebContent\\img\\new-icon16.png\" alt=\"새 글\" />");
  	  
              }
           
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        \r\n");
      out.write("        <td>\r\n");
      out.write("           ");

              if( vo.getWriter().equals("관리자") ){
           
      out.write("<img src=\"D:\\JspWork\\bb5\\WebContent\\img\\manager.png\" alt=\"관리자\" />");
  	  
              }
           
      out.write("\r\n");
      out.write("            <a href=\"mailto:");
      out.print( vo.getEmail() );
      out.write('"');
      out.write('>');
      out.print( vo.getWriter() );
      out.write("</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>");
      out.print( vo.getWritedate() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( vo.getReaded() );
      out.write("</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   ");
        		
        	} // while
        } // if
    
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("    <tfoot>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"5\" align=\"center\">\r\n");
      out.write("           <div class=\"pagination\">   \r\n");
      out.write("             ");

               if( pageBlock.isPrev() ){
             
      out.write("\r\n");
      out.write("             <a href=\"/bb/List?currentPage=");
      out.print( pageBlock.getStart() -1 );
      out.write("\"> &laquo; </a>\r\n");
      out.write("             ");
	   
               } 
                for(int i = pageBlock.getStart() ; i <= pageBlock.getEnd() ; i++ ){
             
      out.write("\r\n");
      out.write("              <a class=\"");
      out.print( i==pageBlock.getCurrentPage() ? "active":""  );
      out.write("\" href=\"List?currentPage=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("             ");
                	
                }
               if( pageBlock.isNext() ){
             
      out.write("\r\n");
      out.write("             <a href=\"/bb/List?currentPage=");
      out.print( pageBlock.getEnd() + 1 );
      out.write("\"> &raquo; </a>\r\n");
      out.write("             ");
	   
               }  
             
      out.write("\r\n");
      out.write("             \r\n");
      out.write("           </div>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td colspan=\"5\" align=\"center\">\r\n");
      out.write("          <form>\r\n");
      out.write("            <select name=\"searchCondition\" id=\"searchCondition\">\r\n");
      out.write("              <option value=\"1\">제목</option>\r\n");
      out.write("              <option value=\"2\">내용</option>\r\n");
      out.write("              <option value=\"3\">글쓴이</option>\r\n");
      out.write("              <option value=\"4\">제목+내용</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" name=\"searchWord\" id=\"searchWord\" />\r\n");
      out.write("            <input type=\"submit\" value=\"search\" />\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </tfoot>\r\n");
      out.write("  </table>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
